### PR TITLE
Withdrawn statuses and flash message for users

### PR DESCRIPTION
**Pull request by adamsilver**
Added **withdrawn by us** and **withdrawn by candidate** statuses

### CODE REVIEW

**Comment by fofr** [comment]
Can you include screens to make these easier to review?

**Comment by adamsilver** [comment]
@fofr can we turn on preview deploys?

**Comment by fofr** [comment]
@adamsilver We should do both. Preview deploys are temporary, and screenshots are useful for code and design archaeologists.

**Comment by adamsilver** [comment]
Okay, will do!

**Pull request merged**
