### PR TITLE
Add ability to change offer provider, course and location

### PR DESCRIPTION
**Pull request by adamsilver**
https://www.loom.com/share/a2953d9e5d6d4204bbcf1b465683e9a2

### CODE REVIEW

**Comment by laurahermionetennant92** [comment]
Hi @adamsilver 
Making notes as I go – my thoughts so far:

Change training provider
That change should be visible here: so that you can see you've changed the provider and the next step is 'Choose course' cos it's choosing a new course to go with the new training provider
Maybe even with a 'Training provider successfully changed'

Screenshot 2020-02-28 at 14 59 38

**Comment by laurahermionetennant92** [comment]
Then this is great with Choose but can we update the details 
Screenshot 2020-02-28 at 15 02 05

**Comment by laurahermionetennant92** [comment]
Course successfully updated banner?
Screenshot 2020-02-28 at 15 26 40

**Comment by laurahermionetennant92** [comment]
Hey – made some content changes in branch but would be good to run through my thinking with you :)

**Comment by adamsilver** [comment]
Next steps agreed on Slack:

1. Add an h2 above the summary list on each question page to say ‘Current offer’ (or similar)

2. H1 on first page of flow should be ‘Change provider’ or whatever it is. Subsequent screens should be ‘Choose course’ (or ‘Choose new course’) or whatever it is.

**Pull request merged**
