### PR TITLE
Filters

### PR DESCRIPTION
**Pull request by adamsilver**
- Add pagination (static for now)
- Add realistic filtering via state and provider
- Add provider field
- Add derived state field to make filtering work more easily
- Tags use accessible colours
- List view is now dumb and gets view-appropriate data passed

Not perfect but almost there ready for research

Screenshots:

image

image

### CODE REVIEW

**Comment by fofr** [comment]
Do users need to manage multiple providers at the same time?

In Publish teaching courses, users manage courses for multiple organisations. But they’re only ever managing one org at once, they make that decision up front when they log in:

https://bat-design-history.herokuapp.com/publish-teacher-training/multiple-organisations

**Comment by adamsilver** [comment]
We are not ignoring that pattern—we are doing this as a test for the next round of research because we think users need to see applications across providers at the same time without having to switch back and forth.

**Comment by fofr** [comment]
Why is Apply filters at the top rather than the bottom of the form?

**Comment by adamsilver** [comment]
So it can be seen if there are more than a handful of filters, and so to
reduce the risk of needing to automatically submit the form with AJAX when
a checkbox is clicked.

Thanks!
Adam

Website: adamsilver.io
Twitter: @adambsilver <http://www.twitter.com/adambsilver/>

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
14/01/20,
19:22:22

**Pull request merged**
