### PR TITLE
Content changes on deferred offer

### PR DESCRIPTION
**Pull request by laurahermionetennant92**
Content changes on deferred offer

### CODE REVIEW

**Comment by laurahermionetennant92** [comment]
Hi Wed am @adamsilver :)
A few outstanding things on this:
1. Hope I've been consistent with my content changes – sometimes hard to find all instances of content in the code.
2. All dates should be written 2021 to 2022 (GDS style) – I couldn't find them all.
3. When we say location is not available, we play back the details (see screengrab) but we don't do this for course details – should we? (Probably)
4. I think Current training cycle (2019 to 2020) is clearer
and would prefer 'View previous or next cycle' to 'Switch cycle' because I think the latter sounds like you are switching a candidate – but let's see how it tests :)
Screenshot 2020-06-30 at 17 36 51

**Comment by adamsilver** [comment]
1. Nice one on the GDS style dates. I will update the other ones to match in this branch.

2. Re: playing back the course – nice spot, yes agree with you, let's play it back

3. I think ‘Current cycle ...’ is okay as is and than plan is to test this in research

4. We thought ‘Switch cycle’ was best overall. One problem with ‘View previous or next cycle’ is that the link text needs to change depending on what cycle you're looking at so you'd need to relearn the UI as the function name changes.

5. I don’t think the change to ‘Update offer’ and the radio button labels works well enough. For background I matched the same pattern as Emma and Paul designed on candidate here https://bat-design-history.netlify.app/apply-for-teacher-training/course-full-after-submitting-initial-approach/ but more importantly ‘Update offer’ doesn't describe the radio buttons and ‘Select alternative...’ as options is what we use during the flow when actually choosing the course/location etc so it's inconsistent with the rest of the content patterns. I think we should go with the plainer ‘Choose a different location’ etc.

6. ‘Deferred offers must be checked and confirmed for the current cycle’ - this feels wrong/off because it's passive and talks about multiple deferred offers. This is about this one deferred application. But I very much like your addition of the word ‘deferral’. How about: ‘You need to reconfirm your deferred offer’

6. ‘Check and reconfirm offer’ button text – I don't think we need the ‘check and’. We don't do that anywhere else and every flow needs checking. I think that's okay and that text only matches 1 of the scenarios (when it's the happy path) and again we'd want this button to be consistent no matter what lies ahead so the flow is as consistent and familiar as possible.

7. ‘We’ll notify the candidate their deferred offer has been checked and confirmed for the current cycle (2021 to 2022). We'll also inform them of any changes you have made.’. For reasons mentioned above can we lose the ‘checked and’. I don't think the candidate needs to be told the provider has checked something.

**Comment by laurahermionetennant92** [comment]
All cool – a few things:

Re no. 5. You originally had 
'Choose action' 
then 'Choose another location'
then 'Select location' 

In the respond to offer flow we have:
Make an offer but change location
Select alternative location
Screenshot 2020-07-02 at 11 59 00

Therefore for consistency suggest we have:
Change details of offer
Change location/change course
Select location/select course

**Comment by laurahermionetennant92** [comment]
Re 6 & 7
We do invite them to check and confirm here.
They check, confirm and then make offer:

Screenshot 2020-07-02 at 11 59 00

'Reconfirm' is ambiguous – what we're asking them to do is check and confirm this offer still stands for the current cycle. 
Agree re passive voice though, so have changed to:
'You must check and confirm this deferred offer for the current cycle'

**Comment by laurahermionetennant92** [comment]
Also 7. I've got 'Confirm offer for current cycle' as the CTA. 
Screenshot 2020-07-02 at 12 28 18

**Comment by laurahermionetennant92** [comment]
8. Agree, is redundant here, will remove :)

**Comment by laurahermionetennant92** [comment]
9. 'Further condition(s) is in contrast to 'Standard conditions' – 'Condition' on its own doesn't work – maybe we can think of an alternative :)

**Comment by laurahermionetennant92** [comment]
@adamsilver Have made changes we discussed on call with Gemma and Bill (think I got them all but lemme know if I missed any!)

**Comment by adamsilver** [comment]
Hey @laurahermionetennant92 went in and tweaked a couple bits like fixing some of the missing ‘to’s and matched the radio button wording.

**Pull request merged**
