### PR TITLE
Stop tracking generated data

### PR DESCRIPTION
**Pull request by paulrobertlloyd**
* Removes `app/data/applications.json` and  `app/data/organisations.json` from git history
* Adds `app/data/applications.json` and  `app/data/organisations.json` to `.gitignore` (rearranged and commented)
* Makes `generate-data` run before `npm start` (potentially controversial)
* Removes `npm run s` (was added when `npm start` was setup to trigger `npm install`, but it no longer does) 
* Updates `README.md`

Am assuming `npm start` is run when deployed to Heroku, meaning data is always generated on a deploy 🤞

### CODE REVIEW

**Comment by paulrobertlloyd** [comment]
Needed to add `build` step for Heroku deploys to work properly.

**Comment by adamsilver** [comment]
I think npm install should regen the data, but not npm start

**Comment by paulrobertlloyd** [comment]
Ah, that would mean not needing `npm run build`, to. Lemme try that.

**Comment by paulrobertlloyd** [comment]
Cool, looks like `postinstall` works.

**Pull request merged**
